import { StyleSheet } from 'react-native';
import { Colors, Fonts, Spacing, Radius, Shadow } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: Spacing[6],
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
  },
  glow: {
    position: 'absolute',
    width: '150%',
    aspectRatio: 1,
    borderRadius: 999,
    backgroundColor: Colors.secondary,
    opacity: 0.12,
    zIndex: -1,
  },
  textContainer: {
    alignItems: 'center',
    width: '100%',
    marginBottom: Spacing[8],
  },
  matchTitle: {
    fontFamily: Fonts.heroic,
    fontSize: 36,
    color: Colors.tertiary,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  matchSubtitle: {
    fontFamily: Fonts.scribe,
    fontSize: 16,
    color: Colors.onSurfaceVariant,
    marginTop: Spacing[1],
    fontStyle: 'italic',
    textAlign: 'center',
  },
  cardsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    flex: 1,
    overflow: 'hidden',
  },
  card: {
    backgroundColor: Colors.surfaceContainer,
    borderRadius: Radius.md,
    borderWidth: 2,
    borderColor: Colors.tertiary,
    ...Shadow.waxSeal,
    elevation: 20,
    overflow: 'hidden',
  },
  imageWrapper: {
    flex: 1,
    backgroundColor: Colors.surfaceVariant,
  },
  image: {
    width: '100%',
    height: '100%',
  },
  placeholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emoji: {
    fontSize: 28,
  },
  cardLabel: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingVertical: Spacing[1],
    paddingHorizontal: Spacing[2],
    alignItems: 'center',
  },
  cardLabelText: {
    fontFamily: Fonts.heroic,
    fontSize: 13,
    color: Colors.onPrimary,
    fontWeight: '700',
  },
  actions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: Spacing[6],
    gap: Spacing[2],
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingTop: Spacing[4],
  },
  primaryButton: {
    backgroundColor: Colors.primary,
    paddingVertical: Spacing[4],
    borderRadius: Radius.sm,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.primaryFixedDim,
    ...Shadow.waxSeal,
  },
  primaryButtonText: {
    fontFamily: Fonts.heroic,
    fontSize: 15,
    fontWeight: '700',
    color: Colors.onPrimary,
    letterSpacing: 1.2,
  },
  secondaryButton: {
    paddingVertical: Spacing[3],
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontFamily: Fonts.scribe,
    fontSize: 15,
    color: Colors.onSurfaceVariant,
    textDecorationLine: 'underline',
  },
});
