// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/profile_events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileEvent_EventType int32

const (
	ProfileEvent_UNKNOWN     ProfileEvent_EventType = 0
	ProfileEvent_UPSERTED    ProfileEvent_EventType = 1
	ProfileEvent_DELETED     ProfileEvent_EventType = 2
	ProfileEvent_ALL_DELETED ProfileEvent_EventType = 3
)

// Enum value maps for ProfileEvent_EventType.
var (
	ProfileEvent_EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "UPSERTED",
		2: "DELETED",
		3: "ALL_DELETED",
	}
	ProfileEvent_EventType_value = map[string]int32{
		"UNKNOWN":     0,
		"UPSERTED":    1,
		"DELETED":     2,
		"ALL_DELETED": 3,
	}
)

func (x ProfileEvent_EventType) Enum() *ProfileEvent_EventType {
	p := new(ProfileEvent_EventType)
	*p = x
	return p
}

func (x ProfileEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_profile_events_proto_enumTypes[0].Descriptor()
}

func (ProfileEvent_EventType) Type() protoreflect.EnumType {
	return &file_proto_profile_events_proto_enumTypes[0]
}

func (x ProfileEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileEvent_EventType.Descriptor instead.
func (ProfileEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_profile_events_proto_rawDescGZIP(), []int{4, 0}
}

type ProfileTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileTag) Reset() {
	*x = ProfileTag{}
	mi := &file_proto_profile_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileTag) ProtoMessage() {}

func (x *ProfileTag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileTag.ProtoReflect.Descriptor instead.
func (*ProfileTag) Descriptor() ([]byte, []int) {
	return file_proto_profile_events_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileTag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileTag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ProfileUpserted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Tagline       *string                `protobuf:"bytes,4,opt,name=tagline,proto3,oneof" json:"tagline,omitempty"`
	Bio           *string                `protobuf:"bytes,5,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,6,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Age           *int32                 `protobuf:"varint,8,opt,name=age,proto3,oneof" json:"age,omitempty"`
	IsOc          *bool                  `protobuf:"varint,9,opt,name=is_oc,json=isOc,proto3,oneof" json:"is_oc,omitempty"`
	Gender        []*ProfileTag          `protobuf:"bytes,10,rep,name=gender,proto3" json:"gender,omitempty"`
	Race          []*ProfileTag          `protobuf:"bytes,11,rep,name=race,proto3" json:"race,omitempty"`
	Fandom        []*ProfileTag          `protobuf:"bytes,12,rep,name=fandom,proto3" json:"fandom,omitempty"`
	Interests     []*ProfileTag          `protobuf:"bytes,13,rep,name=interests,proto3" json:"interests,omitempty"`
	Events        []*ProfileTag          `protobuf:"bytes,14,rep,name=events,proto3" json:"events,omitempty"`
	LookingFor    []*ProfileTag          `protobuf:"bytes,15,rep,name=looking_for,json=lookingFor,proto3" json:"looking_for,omitempty"`
	Generated     bool                   `protobuf:"varint,16,opt,name=generated,proto3" json:"generated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpserted) Reset() {
	*x = ProfileUpserted{}
	mi := &file_proto_profile_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpserted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpserted) ProtoMessage() {}

func (x *ProfileUpserted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpserted.ProtoReflect.Descriptor instead.
func (*ProfileUpserted) Descriptor() ([]byte, []int) {
	return file_proto_profile_events_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileUpserted) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProfileUpserted) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileUpserted) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProfileUpserted) GetTagline() string {
	if x != nil && x.Tagline != nil {
		return *x.Tagline
	}
	return ""
}

func (x *ProfileUpserted) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *ProfileUpserted) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *ProfileUpserted) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProfileUpserted) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *ProfileUpserted) GetIsOc() bool {
	if x != nil && x.IsOc != nil {
		return *x.IsOc
	}
	return false
}

func (x *ProfileUpserted) GetGender() []*ProfileTag {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *ProfileUpserted) GetRace() []*ProfileTag {
	if x != nil {
		return x.Race
	}
	return nil
}

func (x *ProfileUpserted) GetFandom() []*ProfileTag {
	if x != nil {
		return x.Fandom
	}
	return nil
}

func (x *ProfileUpserted) GetInterests() []*ProfileTag {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *ProfileUpserted) GetEvents() []*ProfileTag {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ProfileUpserted) GetLookingFor() []*ProfileTag {
	if x != nil {
		return x.LookingFor
	}
	return nil
}

func (x *ProfileUpserted) GetGenerated() bool {
	if x != nil {
		return x.Generated
	}
	return false
}

type ProfileDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileDeleted) Reset() {
	*x = ProfileDeleted{}
	mi := &file_proto_profile_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileDeleted) ProtoMessage() {}

func (x *ProfileDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileDeleted.ProtoReflect.Descriptor instead.
func (*ProfileDeleted) Descriptor() ([]byte, []int) {
	return file_proto_profile_events_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileDeleted) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type AllProfilesDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   string                 `protobuf:"bytes,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllProfilesDeleted) Reset() {
	*x = AllProfilesDeleted{}
	mi := &file_proto_profile_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllProfilesDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllProfilesDeleted) ProtoMessage() {}

func (x *AllProfilesDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllProfilesDeleted.ProtoReflect.Descriptor instead.
func (*AllProfilesDeleted) Descriptor() ([]byte, []int) {
	return file_proto_profile_events_proto_rawDescGZIP(), []int{3}
}

func (x *AllProfilesDeleted) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

func (x *AllProfilesDeleted) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ProfileEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ProfileEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=profile.ProfileEvent_EventType" json:"type,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ProfileEvent_Upserted
	//	*ProfileEvent_Deleted
	//	*ProfileEvent_AllDeleted
	Event         isProfileEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileEvent) Reset() {
	*x = ProfileEvent{}
	mi := &file_proto_profile_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileEvent) ProtoMessage() {}

func (x *ProfileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileEvent.ProtoReflect.Descriptor instead.
func (*ProfileEvent) Descriptor() ([]byte, []int) {
	return file_proto_profile_events_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileEvent) GetType() ProfileEvent_EventType {
	if x != nil {
		return x.Type
	}
	return ProfileEvent_UNKNOWN
}

func (x *ProfileEvent) GetEvent() isProfileEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ProfileEvent) GetUpserted() *ProfileUpserted {
	if x != nil {
		if x, ok := x.Event.(*ProfileEvent_Upserted); ok {
			return x.Upserted
		}
	}
	return nil
}

func (x *ProfileEvent) GetDeleted() *ProfileDeleted {
	if x != nil {
		if x, ok := x.Event.(*ProfileEvent_Deleted); ok {
			return x.Deleted
		}
	}
	return nil
}

func (x *ProfileEvent) GetAllDeleted() *AllProfilesDeleted {
	if x != nil {
		if x, ok := x.Event.(*ProfileEvent_AllDeleted); ok {
			return x.AllDeleted
		}
	}
	return nil
}

type isProfileEvent_Event interface {
	isProfileEvent_Event()
}

type ProfileEvent_Upserted struct {
	Upserted *ProfileUpserted `protobuf:"bytes,2,opt,name=upserted,proto3,oneof"`
}

type ProfileEvent_Deleted struct {
	Deleted *ProfileDeleted `protobuf:"bytes,3,opt,name=deleted,proto3,oneof"`
}

type ProfileEvent_AllDeleted struct {
	AllDeleted *AllProfilesDeleted `protobuf:"bytes,4,opt,name=all_deleted,json=allDeleted,proto3,oneof"`
}

func (*ProfileEvent_Upserted) isProfileEvent_Event() {}

func (*ProfileEvent_Deleted) isProfileEvent_Event() {}

func (*ProfileEvent_AllDeleted) isProfileEvent_Event() {}

var File_proto_profile_events_proto protoreflect.FileDescriptor

const file_proto_profile_events_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/profile_events.proto\x12\aprofile\"D\n" +
	"\n" +
	"ProfileTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"\xec\x04\n" +
	"\x0fProfileUpserted\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\atagline\x18\x04 \x01(\tH\x00R\atagline\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\x05 \x01(\tH\x01R\x03bio\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x06 \x03(\tR\timageUrls\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x15\n" +
	"\x03age\x18\b \x01(\x05H\x02R\x03age\x88\x01\x01\x12\x18\n" +
	"\x05is_oc\x18\t \x01(\bH\x03R\x04isOc\x88\x01\x01\x12+\n" +
	"\x06gender\x18\n" +
	" \x03(\v2\x13.profile.ProfileTagR\x06gender\x12'\n" +
	"\x04race\x18\v \x03(\v2\x13.profile.ProfileTagR\x04race\x12+\n" +
	"\x06fandom\x18\f \x03(\v2\x13.profile.ProfileTagR\x06fandom\x121\n" +
	"\tinterests\x18\r \x03(\v2\x13.profile.ProfileTagR\tinterests\x12+\n" +
	"\x06events\x18\x0e \x03(\v2\x13.profile.ProfileTagR\x06events\x124\n" +
	"\vlooking_for\x18\x0f \x03(\v2\x13.profile.ProfileTagR\n" +
	"lookingFor\x12\x1c\n" +
	"\tgenerated\x18\x10 \x01(\bR\tgeneratedB\n" +
	"\n" +
	"\b_taglineB\x06\n" +
	"\x04_bioB\x06\n" +
	"\x04_ageB\b\n" +
	"\x06_is_oc\"/\n" +
	"\x0eProfileDeleted\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"V\n" +
	"\x12AllProfilesDeleted\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\tR\vadminUserId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"\xbf\x02\n" +
	"\fProfileEvent\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.profile.ProfileEvent.EventTypeR\x04type\x126\n" +
	"\bupserted\x18\x02 \x01(\v2\x18.profile.ProfileUpsertedH\x00R\bupserted\x123\n" +
	"\adeleted\x18\x03 \x01(\v2\x17.profile.ProfileDeletedH\x00R\adeleted\x12>\n" +
	"\vall_deleted\x18\x04 \x01(\v2\x1b.profile.AllProfilesDeletedH\x00R\n" +
	"allDeleted\"D\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bUPSERTED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02\x12\x0f\n" +
	"\vALL_DELETED\x10\x03B\a\n" +
	"\x05eventB\tZ\a./protob\x06proto3"

var (
	file_proto_profile_events_proto_rawDescOnce sync.Once
	file_proto_profile_events_proto_rawDescData []byte
)

func file_proto_profile_events_proto_rawDescGZIP() []byte {
	file_proto_profile_events_proto_rawDescOnce.Do(func() {
		file_proto_profile_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_events_proto_rawDesc), len(file_proto_profile_events_proto_rawDesc)))
	})
	return file_proto_profile_events_proto_rawDescData
}

var file_proto_profile_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_profile_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_profile_events_proto_goTypes = []any{
	(ProfileEvent_EventType)(0), // 0: profile.ProfileEvent.EventType
	(*ProfileTag)(nil),          // 1: profile.ProfileTag
	(*ProfileUpserted)(nil),     // 2: profile.ProfileUpserted
	(*ProfileDeleted)(nil),      // 3: profile.ProfileDeleted
	(*AllProfilesDeleted)(nil),  // 4: profile.AllProfilesDeleted
	(*ProfileEvent)(nil),        // 5: profile.ProfileEvent
}
var file_proto_profile_events_proto_depIdxs = []int32{
	1,  // 0: profile.ProfileUpserted.gender:type_name -> profile.ProfileTag
	1,  // 1: profile.ProfileUpserted.race:type_name -> profile.ProfileTag
	1,  // 2: profile.ProfileUpserted.fandom:type_name -> profile.ProfileTag
	1,  // 3: profile.ProfileUpserted.interests:type_name -> profile.ProfileTag
	1,  // 4: profile.ProfileUpserted.events:type_name -> profile.ProfileTag
	1,  // 5: profile.ProfileUpserted.looking_for:type_name -> profile.ProfileTag
	0,  // 6: profile.ProfileEvent.type:type_name -> profile.ProfileEvent.EventType
	2,  // 7: profile.ProfileEvent.upserted:type_name -> profile.ProfileUpserted
	3,  // 8: profile.ProfileEvent.deleted:type_name -> profile.ProfileDeleted
	4,  // 9: profile.ProfileEvent.all_deleted:type_name -> profile.AllProfilesDeleted
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_profile_events_proto_init() }
func file_proto_profile_events_proto_init() {
	if File_proto_profile_events_proto != nil {
		return
	}
	file_proto_profile_events_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_profile_events_proto_msgTypes[4].OneofWrappers = []any{
		(*ProfileEvent_Upserted)(nil),
		(*ProfileEvent_Deleted)(nil),
		(*ProfileEvent_AllDeleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_events_proto_rawDesc), len(file_proto_profile_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_profile_events_proto_goTypes,
		DependencyIndexes: file_proto_profile_events_proto_depIdxs,
		EnumInfos:         file_proto_profile_events_proto_enumTypes,
		MessageInfos:      file_proto_profile_events_proto_msgTypes,
	}.Build()
	File_proto_profile_events_proto = out.File
	file_proto_profile_events_proto_goTypes = nil
	file_proto_profile_events_proto_depIdxs = nil
}
