// Code generated by protoc-gen-go. DO NOT EDIT.
// source: match_events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchEvent_EventType int32

const (
	MatchEvent_UNKNOWN MatchEvent_EventType = 0
	MatchEvent_CREATED MatchEvent_EventType = 1
	MatchEvent_DELETED MatchEvent_EventType = 2
)

var (
	MatchEvent_EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATED",
		2: "DELETED",
	}
	MatchEvent_EventType_value = map[string]int32{
		"UNKNOWN": 0,
		"CREATED": 1,
		"DELETED": 2,
	}
)

func (x MatchEvent_EventType) Enum() *MatchEvent_EventType {
	p := new(MatchEvent_EventType)
	*p = x
	return p
}

func (x MatchEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_match_events_proto_enumTypes[0].Descriptor()
}

func (MatchEvent_EventType) Type() protoreflect.EnumType {
	return &file_match_events_proto_enumTypes[0]
}

func (x MatchEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (MatchEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_match_events_proto_rawDescGZIP(), []int{2, 0}
}

type MatchCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	ProfileIds    []string               `protobuf:"bytes,2,rep,name=profile_ids,json=profileIds,proto3" json:"profile_ids,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCreated) Reset() {
	*x = MatchCreated{}
	mi := &file_match_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCreated) ProtoMessage() {}

func (x *MatchCreated) ProtoReflect() protoreflect.Message {
	mi := &file_match_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*MatchCreated) Descriptor() ([]byte, []int) {
	return file_match_events_proto_rawDescGZIP(), []int{0}
}

func (x *MatchCreated) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchCreated) GetProfileIds() []string {
	if x != nil {
		return x.ProfileIds
	}
	return nil
}

func (x *MatchCreated) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MatchDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchDeleted) Reset() {
	*x = MatchDeleted{}
	mi := &file_match_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchDeleted) ProtoMessage() {}

func (x *MatchDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_match_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*MatchDeleted) Descriptor() ([]byte, []int) {
	return file_match_events_proto_rawDescGZIP(), []int{1}
}

func (x *MatchDeleted) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type MatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MatchEvent_EventType   `protobuf:"varint,1,opt,name=type,proto3,enum=discovery.MatchEvent_EventType" json:"type,omitempty"`
	Event         isMatchEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEvent) Reset() {
	*x = MatchEvent{}
	mi := &file_match_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEvent) ProtoMessage() {}

func (x *MatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_match_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*MatchEvent) Descriptor() ([]byte, []int) {
	return file_match_events_proto_rawDescGZIP(), []int{2}
}

func (x *MatchEvent) GetType() MatchEvent_EventType {
	if x != nil {
		return x.Type
	}
	return MatchEvent_UNKNOWN
}

func (x *MatchEvent) GetEvent() isMatchEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MatchEvent) GetCreated() *MatchCreated {
	if x != nil {
		if x, ok := x.Event.(*MatchEvent_Created); ok {
			return x.Created
		}
	}
	return nil
}

func (x *MatchEvent) GetDeleted() *MatchDeleted {
	if x != nil {
		if x, ok := x.Event.(*MatchEvent_Deleted); ok {
			return x.Deleted
		}
	}
	return nil
}

type isMatchEvent_Event interface {
	isMatchEvent_Event()
}

type MatchEvent_Created struct {
	Created *MatchCreated `protobuf:"bytes,2,opt,name=created,proto3,oneof"`
}

type MatchEvent_Deleted struct {
	Deleted *MatchDeleted `protobuf:"bytes,3,opt,name=deleted,proto3,oneof"`
}

func (*MatchEvent_Created) isMatchEvent_Event() {}

func (*MatchEvent_Deleted) isMatchEvent_Event() {}

var File_match_events_proto protoreflect.FileDescriptor

const file_match_events_proto_rawDesc = "" +
	"\n" +
	"\x12match_events.proto\x12\tdiscovery\"i\n" +
	"\fMatchCreated\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1f\n" +
	"\vprofile_ids\x18\x02 \x03(\tR\n" +
	"profileIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\")\n" +
	"\fMatchDeleted\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"\xe8\x01\n" +
	"\n" +
	"MatchEvent\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.discovery.MatchEvent.EventTypeR\x04type\x123\n" +
	"\acreated\x18\x02 \x01(\v2\x17.discovery.MatchCreatedH\x00R\acreated\x123\n" +
	"\adeleted\x18\x03 \x01(\v2\x17.discovery.MatchDeletedH\x00R\adeleted\"2\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02B\a\n" +
	"\x05eventB\tZ\a./protob\x06proto3"

var (
	file_match_events_proto_rawDescOnce sync.Once
	file_match_events_proto_rawDescData []byte
)

func file_match_events_proto_rawDescGZIP() []byte {
	file_match_events_proto_rawDescOnce.Do(func() {
		file_match_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_match_events_proto_rawDesc), len(file_match_events_proto_rawDesc)))
	})
	return file_match_events_proto_rawDescData
}

var file_match_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_match_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_match_events_proto_goTypes = []any{
	(MatchEvent_EventType)(0), // 0: discovery.MatchEvent.EventType
	(*MatchCreated)(nil),      // 1: discovery.MatchCreated
	(*MatchDeleted)(nil),      // 2: discovery.MatchDeleted
	(*MatchEvent)(nil),        // 3: discovery.MatchEvent
}
var file_match_events_proto_depIdxs = []int32{
	0, // 0: discovery.MatchEvent.type:type_name -> discovery.MatchEvent.EventType
	1, // 1: discovery.MatchEvent.created:type_name -> discovery.MatchCreated
	2, // 2: discovery.MatchEvent.deleted:type_name -> discovery.MatchDeleted
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_match_events_proto_init() }
func file_match_events_proto_init() {
	if File_match_events_proto != nil {
		return
	}
	file_match_events_proto_msgTypes[2].OneofWrappers = []any{
		(*MatchEvent_Created)(nil),
		(*MatchEvent_Deleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_match_events_proto_rawDesc), len(file_match_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_events_proto_goTypes,
		DependencyIndexes: file_match_events_proto_depIdxs,
		EnumInfos:         file_match_events_proto_enumTypes,
		MessageInfos:      file_match_events_proto_msgTypes,
	}.Build()
	File_match_events_proto = out.File
	file_match_events_proto_goTypes = nil
	file_match_events_proto_depIdxs = nil
}
