syntax = "proto3";

package profile;

message ProfileUpserted {
    string profile_id = 1;
    string user_id = 2;
    string display_name = 3;
    optional string tagline = 4;
    optional string bio = 5;
    repeated string image_urls = 6;
    optional string gender = 7;
    bool is_active = 8;
}

message ProfileDeleted {
    string profile_id = 1;
}

message AllProfilesDeleted {
    string admin_user_id = 1;
    string timestamp = 2;
}

message ProfileEvent {
    enum EventType {
        UNKNOWN = 0;
        UPSERTED = 1;
        DELETED = 2;
        ALL_DELETED = 3;
    }
    EventType type = 1;
    oneof event {
        ProfileUpserted upserted = 2;
        ProfileDeleted deleted = 3;
        AllProfilesDeleted all_deleted = 4;
    }
}
