import { StyleSheet, Platform } from 'react-native';
import { Colors, Fonts, Spacing, Radius, Shadow } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.surface,
  },
  profileTabsContainer: {
    backgroundColor: Colors.surfaceContainerLowest,
    paddingVertical: Spacing[4],
    borderBottomWidth: 1,
    borderBottomColor: Colors.outlineVariant,
  },
  profileTabsContent: {
    paddingHorizontal: Spacing[6],
    gap: Spacing[4],
  },
  profileTab: {
    height: 100,
    aspectRatio: 9 / 16,
    borderRadius: Radius.sm,
    overflow: 'hidden',
    backgroundColor: Colors.surfaceContainerLow,
    borderWidth: 2,
    borderColor: 'transparent',
    ...Shadow.waxSeal,
  },
  activeProfileTab: {
    borderColor: Colors.tertiary,
  },
  profileTabImage: {
    width: '100%',
    height: '100%',
  },
  profileTabOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
    padding: 4,
  },
  activeProfileTabOverlay: {
    backgroundColor: 'rgba(0,0,0,0.1)',
  },
  profileTabName: {
    fontFamily: Fonts.scribe,
    fontSize: 10,
    color: Colors.onPrimary,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  activeProfileTabName: {
    color: Colors.tertiary,
  },
  sectionHeader: {
    paddingHorizontal: Spacing[6],
    paddingTop: Spacing[6],
    paddingBottom: Spacing[2],
  },
  sectionTitle: {
    fontFamily: Fonts.heroic,
    fontSize: 18,
    color: Colors.onSurface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.outlineVariant,
    paddingBottom: Spacing[1],
  },
  newMatchesContainer: {
    paddingVertical: Spacing[3],
  },
  newMatchesContent: {
    paddingHorizontal: Spacing[6],
    gap: Spacing[4],
  },
  newMatchItem: {
    width: 56, // height 100 * 9/16 ≈ 56
    alignItems: 'center',
  },
  newMatchImage: {
    width: '100%',
    height: 100,
    aspectRatio: 9 / 16,
    borderRadius: Radius.sm,
    backgroundColor: Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
  },
  newMatchAddButton: {
    width: '100%',
    height: 100,
    aspectRatio: 9 / 16,
    borderRadius: Radius.sm,
    backgroundColor: Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    justifyContent: 'center',
    alignItems: 'center',
  },
  newMatchName: {
    fontFamily: Fonts.scribe,
    fontSize: 12,
    color: Colors.outline,
    marginTop: 4,
  },
  inboxContainer: {
    paddingHorizontal: Spacing[6],
    gap: Spacing[4],
    marginTop: Spacing[2],
  },
  inboxItem: {
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: Radius.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    ...Shadow.waxSeal,
    ...(Platform.OS === 'web' ? { cursor: 'pointer' } : {}),
  },
  inboxContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing[2],
  },
  inboxBanner: {
    width: 32,
    height: 56,
    backgroundColor: Colors.surfaceContainerLowest,
  },
  inboxTextContainer: {
    flex: 1,
    paddingLeft: Spacing[4],
    paddingRight: Spacing[4],
    justifyContent: 'center',
  },
  inboxName: {
    fontFamily: Fonts.heroic,
    fontSize: 16,
    color: Colors.primary,
  },
  inboxLastMessage: {
    fontFamily: Fonts.scribe,
    fontSize: 13,
    color: Colors.outline,
    marginTop: 2,
  },
  emptyText: {
    fontFamily: Fonts.scribe,
    fontSize: 14,
    color: Colors.outline,
    textAlign: 'center',
    marginTop: Spacing[4],
    fontStyle: 'italic',
  },
  headerSub: {
    fontFamily: Fonts.scribe,
    fontSize: 14,
    color: Colors.outline,
  },
  unreadDot: {
    position: 'absolute',
    top: -2,
    left: -2,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.error,
    borderWidth: 2,
    borderColor: Colors.surfaceContainerLow,
  },
  inboxAvatarContainer: {
    position: 'relative',
  },
  profileUnreadDot: {
    position: 'absolute',
    top: -2,
    left: -2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: Colors.error,
    borderWidth: 2,
    borderColor: Colors.surfaceContainerLowest,
  },

  // Stacked Avatars for Group Conversations
  stackedAvatarsContainer: {
    width: 52,
    height: 56,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stackedAvatarCard: {
    position: 'absolute',
    width: 26,
    height: 44,
    borderRadius: Radius.xs,
    borderWidth: 1.5,
    borderColor: Colors.surfaceContainerLow,
    backgroundColor: Colors.surfaceContainerLowest,
    overflow: 'hidden',
    ...Shadow.waxSeal,
  },
  stackedAvatarImage: {
    width: '100%',
    height: '100%',
  },
  partyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerHigh,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: Radius.xs,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    gap: 3,
  },
  partyBadgeText: {
    fontFamily: Fonts.scribe,
    fontSize: 10,
    color: Colors.outline,
    fontWeight: '600',
    textTransform: 'uppercase',
  },

  // Gather Party Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing[4],
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '80%',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: Radius.lg,
    padding: Spacing[5],
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    ...Shadow.waxSeal,
  },
  modalTitle: {
    fontFamily: Fonts.heroic,
    fontSize: 20,
    color: Colors.primary,
    marginBottom: Spacing[1],
    textAlign: 'center',
  },
  modalSubtitle: {
    fontFamily: Fonts.scribe,
    fontSize: 13,
    color: Colors.outline,
    marginBottom: Spacing[4],
    textAlign: 'center',
  },
  groupInput: {
    backgroundColor: Colors.surfaceContainerHigh,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing[4],
    paddingVertical: Spacing[3],
    color: Colors.onSurface,
    fontFamily: Fonts.scribe,
    fontSize: 15,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    marginBottom: Spacing[4],
  },
  companionListTitle: {
    fontFamily: Fonts.heroic,
    fontSize: 14,
    color: Colors.onSurface,
    marginBottom: Spacing[2],
  },
  companionScroll: {
    maxHeight: 220,
    marginBottom: Spacing[4],
  },
  companionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing[2],
    paddingHorizontal: Spacing[3],
    borderRadius: Radius.sm,
    marginBottom: Spacing[2],
    backgroundColor: Colors.surfaceContainer,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
  },
  companionItemActive: {
    borderColor: Colors.tertiary,
    backgroundColor: Colors.surfaceContainerHigh,
  },
  companionAvatar: {
    width: 36,
    height: 36,
    borderRadius: Radius.full,
    marginRight: Spacing[3],
  },
  companionName: {
    flex: 1,
    fontFamily: Fonts.scribe,
    fontSize: 14,
    color: Colors.onSurface,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: Radius.xs,
    borderWidth: 1.5,
    borderColor: Colors.outline,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxActive: {
    backgroundColor: Colors.tertiary,
    borderColor: Colors.tertiary,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: Spacing[3],
    marginTop: Spacing[2],
  },
  cancelButton: {
    paddingVertical: Spacing[2],
    paddingHorizontal: Spacing[4],
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.outline,
  },
  cancelButtonText: {
    fontFamily: Fonts.scribe,
    fontSize: 14,
    color: Colors.outline,
  },
  createButton: {
    paddingVertical: Spacing[2],
    paddingHorizontal: Spacing[4],
    borderRadius: Radius.md,
    backgroundColor: Colors.tertiary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  createButtonDisabled: {
    opacity: 0.5,
  },
  createButtonText: {
    fontFamily: Fonts.heroic,
    fontSize: 14,
    color: Colors.onTertiary,
  },
});
