#!/usr/bin/env python3
import os
import re
import json
import sys

def parse_ambr(file_path):
    """
    Parses a Syrupy .ambr file.
    Format:
    # serializer version: 1
    # name: snapshot_name
      dict({
        ...
      })
    # ---
    """
    with open(file_path, "r") as f:
        content = f.read()

    # Split by the separator
    parts = re.split(r"# ---\n", content)
    snapshots = {}

    for part in parts:
        name_match = re.search(r"# name: (.*)\n", part)
        if not name_match:
            continue
        
        name = name_match.group(1).strip()
        # Find the content starting from the first non-comment line
        lines = part.split("\n")
        data_lines = []
        started = False
        for line in lines:
            if line.startswith("#"):
                continue
            if not started and not line.strip():
                continue
            started = True
            data_lines.append(line)
        
        data_str = "\n".join(data_lines).strip()
        if not data_str:
            continue
            
        # Syrupy's ambr format is effectively Python code for basic types.
        # We can use eval if we replace 'dict({' with '{' and 'list([' with '['
        # but that's risky. A better way is to use a basic parser.
        # For simplicity and given this is a controlled environment, we use a 
        # cleanup + eval approach but only for known SAFE constructs.
        
        # Cleanup Syrupy-specific wrappers
        clean_data = data_str
        clean_data = re.sub(r"dict\(\{", "{", clean_data)
        clean_data = re.sub(r"list\(\[", "[", clean_data)
        clean_data = re.sub(r"\}\)", "}", clean_data)
        clean_data = re.sub(r"\]\)", "]", clean_data)
        
        try:
            # eval is safe here because the input is generated by our own tests
            val = eval(clean_data, {"__builtins__": {}}, {})
            snapshots[name] = val
        except Exception as e:
            print(f"Error parsing snapshot '{name}' in {file_path}: {e}")
            # Fallback: just store the raw string if eval fails
            snapshots[name] = data_str

    return snapshots

def main():
    if len(sys.argv) < 2:
        print("Usage: convert_snapshots.py <service_path>")
        sys.exit(1)

    service_path = sys.argv[1]
    snapshots_dir = os.path.join(service_path, "tests", "__snapshots__")
    
    if not os.path.exists(snapshots_dir):
        print(f"No snapshots found in {snapshots_dir}")
        sys.exit(1)

    all_snapshots = {}
    for filename in os.listdir(snapshots_dir):
        if filename.endswith(".ambr"):
            file_path = os.path.join(snapshots_dir, filename)
            print(f"Processing {file_path}...")
            snaps = parse_ambr(file_path)
            all_snapshots.update(snaps)

    output_path = os.path.join(service_path, "snapshots.json")
    with open(output_path, "w") as f:
        json.dump(all_snapshots, f, indent=2)
    
    print(f"Successfully generated {output_path} with {len(all_snapshots)} snapshots.")

if __name__ == "__main__":
    main()
