import { StyleSheet, Platform } from 'react-native';
import { Colors, Fonts, Spacing, Radius, Shadow } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.surface,
  },
  testerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.surfaceContainerHighest,
    paddingVertical: Spacing[2],
    marginHorizontal: Spacing[4],
    marginBottom: Spacing[4],
    borderRadius: Radius.sm,
    gap: Spacing[2],
    borderWidth: 1,
    borderColor: Colors.tertiaryContainer,
  },
  testerText: {
    fontFamily: Fonts.scribe,
    fontSize: 12,
    fontWeight: '700',
    color: Colors.tertiary,
    letterSpacing: 1,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.surface,
  },
  loadingText: {
    marginTop: Spacing[4],
    fontFamily: Fonts.scribe,
    color: Colors.outline,
    letterSpacing: 1,
  },
  listContent: {
    padding: Spacing[4],
    gap: Spacing[4],
  },
  cardContainer: {
    marginBottom: Spacing[2],
  },
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing[4],
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    ...Shadow.waxSeal,
  },
  activeProfileCard: {
    borderColor: Colors.primary,
    backgroundColor: Colors.surfaceContainerHigh,
  },
  profileImageContainer: {
    position: 'relative',
    marginRight: Spacing[4],
  },
  profileImage: {
    height: 80,
    aspectRatio: 9 / 16,
    borderRadius: Radius.sm,
    backgroundColor: Colors.surfaceVariant,
  },
  profileImagePlaceholder: {
    height: 80,
    aspectRatio: 9 / 16,
    borderRadius: Radius.sm,
    backgroundColor: Colors.surfaceVariant,
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderEmoji: {
    fontSize: 20,
  },
  activeBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: Colors.surface,
    borderRadius: 10,
    zIndex: 1,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontFamily: Fonts.heroic,
    fontSize: 18,
    color: Colors.onSurface,
    marginBottom: 2,
  },
  cardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing[2],
  },
  actionButton: {
    padding: Spacing[4],
    ...(Platform.OS === 'web' ? { cursor: 'pointer' } : {}),
  },
  selectionIndicator: {
    marginLeft: Spacing[1],
  },
  profileClass: {
    fontFamily: Fonts.scribe,
    fontSize: 12,
    color: Colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  profileTagline: {
    fontFamily: Fonts.scribe,
    fontSize: 13,
    color: Colors.outline,
    marginTop: 4,
    fontStyle: 'italic',
  },
  emptyIcon: {
    fontSize: 64,
    marginBottom: Spacing[4],
  },
  emptyTitle: {
    fontFamily: Fonts.heroic,
    fontSize: 24,
    color: Colors.onSurface,
    marginBottom: Spacing[2],
  },
  emptyDesc: {
    fontFamily: Fonts.scribe,
    fontSize: 14,
    color: Colors.outline,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: Spacing[8],
    paddingHorizontal: Spacing[6],
  },
  emptyCtaButton: {
    width: 'auto' as any,
    paddingHorizontal: Spacing[6],
    height: 64,
    borderRadius: Radius.md,
    borderWidth: 2,
    borderColor: Colors.primary,
    backgroundColor: Colors.surfaceContainerLowest,
    justifyContent: 'center',
    alignItems: 'center',
    ...Shadow.waxSeal,
  },
  emptyCtaText: {
    color: Colors.primary,
    fontFamily: Fonts.scribe,
    fontWeight: '600' as const,
    letterSpacing: 1,
  },
  addProfileButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing[4],
    backgroundColor: Colors.surfaceContainerLowest,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    borderStyle: 'dashed',
    marginTop: Spacing[2],
    marginBottom: Spacing[10],
  },
  addIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.surfaceContainerLow,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing[4],
  },
  addProfileText: {
    fontFamily: Fonts.heroic,
    fontSize: 18,
    color: Colors.primary,
  }
});
