// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent_events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRequestEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AgentName       string                 `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Prompt          string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	MessageType     string                 `protobuf:"bytes,5,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`    // "user", "system", "event"
	MetadataJson    string                 `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"` // JSON-encoded metadata
	BotProfileId    string                 `protobuf:"bytes,7,opt,name=bot_profile_id,json=botProfileId,proto3" json:"bot_profile_id,omitempty"`
	BotUserId       string                 `protobuf:"bytes,8,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	SenderProfileId string                 `protobuf:"bytes,9,opt,name=sender_profile_id,json=senderProfileId,proto3" json:"sender_profile_id,omitempty"`
	BehaviorType    string                 `protobuf:"bytes,10,opt,name=behavior_type,json=behaviorType,proto3" json:"behavior_type,omitempty"`
	Timestamp       string                 `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC3339
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentRequestEvent) Reset() {
	*x = AgentRequestEvent{}
	mi := &file_proto_agent_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequestEvent) ProtoMessage() {}

func (x *AgentRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequestEvent.ProtoReflect.Descriptor instead.
func (*AgentRequestEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_events_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRequestEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentRequestEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentRequestEvent) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentRequestEvent) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AgentRequestEvent) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *AgentRequestEvent) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *AgentRequestEvent) GetBotProfileId() string {
	if x != nil {
		return x.BotProfileId
	}
	return ""
}

func (x *AgentRequestEvent) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *AgentRequestEvent) GetSenderProfileId() string {
	if x != nil {
		return x.SenderProfileId
	}
	return ""
}

func (x *AgentRequestEvent) GetBehaviorType() string {
	if x != nil {
		return x.BehaviorType
	}
	return ""
}

func (x *AgentRequestEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type AgentResponseEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	BotProfileId    string                 `protobuf:"bytes,3,opt,name=bot_profile_id,json=botProfileId,proto3" json:"bot_profile_id,omitempty"`
	BotUserId       string                 `protobuf:"bytes,4,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	SenderProfileId string                 `protobuf:"bytes,5,opt,name=sender_profile_id,json=senderProfileId,proto3" json:"sender_profile_id,omitempty"`
	BehaviorType    string                 `protobuf:"bytes,6,opt,name=behavior_type,json=behaviorType,proto3" json:"behavior_type,omitempty"`
	AgentName       string                 `protobuf:"bytes,7,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                                 // "SUCCESS" or "ERROR"
	ResponseJson    string                 `protobuf:"bytes,9,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"` // JSON array of parsed message/narration items
	ErrorMessage    string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	MetadataJson    string                 `protobuf:"bytes,11,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Timestamp       string                 `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC3339
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentResponseEvent) Reset() {
	*x = AgentResponseEvent{}
	mi := &file_proto_agent_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponseEvent) ProtoMessage() {}

func (x *AgentResponseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponseEvent.ProtoReflect.Descriptor instead.
func (*AgentResponseEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_events_proto_rawDescGZIP(), []int{1}
}

func (x *AgentResponseEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentResponseEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentResponseEvent) GetBotProfileId() string {
	if x != nil {
		return x.BotProfileId
	}
	return ""
}

func (x *AgentResponseEvent) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *AgentResponseEvent) GetSenderProfileId() string {
	if x != nil {
		return x.SenderProfileId
	}
	return ""
}

func (x *AgentResponseEvent) GetBehaviorType() string {
	if x != nil {
		return x.BehaviorType
	}
	return ""
}

func (x *AgentResponseEvent) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentResponseEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentResponseEvent) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

func (x *AgentResponseEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AgentResponseEvent) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *AgentResponseEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_agent_events_proto protoreflect.FileDescriptor

const file_proto_agent_events_proto_rawDesc = "" +
	"\n" +
	"\x18proto/agent_events.proto\x12\x05agent\"\x8f\x03\n" +
	"\x11AgentRequestEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x03 \x01(\tR\tagentName\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12!\n" +
	"\fmessage_type\x18\x05 \x01(\tR\vmessageType\x12#\n" +
	"\rmetadata_json\x18\x06 \x01(\tR\fmetadataJson\x12$\n" +
	"\x0ebot_profile_id\x18\a \x01(\tR\fbotProfileId\x12\x1e\n" +
	"\vbot_user_id\x18\b \x01(\tR\tbotUserId\x12*\n" +
	"\x11sender_profile_id\x18\t \x01(\tR\x0fsenderProfileId\x12#\n" +
	"\rbehavior_type\x18\n" +
	" \x01(\tR\fbehaviorType\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\tR\ttimestamp\"\xb7\x03\n" +
	"\x12AgentResponseEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12$\n" +
	"\x0ebot_profile_id\x18\x03 \x01(\tR\fbotProfileId\x12\x1e\n" +
	"\vbot_user_id\x18\x04 \x01(\tR\tbotUserId\x12*\n" +
	"\x11sender_profile_id\x18\x05 \x01(\tR\x0fsenderProfileId\x12#\n" +
	"\rbehavior_type\x18\x06 \x01(\tR\fbehaviorType\x12\x1d\n" +
	"\n" +
	"agent_name\x18\a \x01(\tR\tagentName\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12#\n" +
	"\rresponse_json\x18\t \x01(\tR\fresponseJson\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12#\n" +
	"\rmetadata_json\x18\v \x01(\tR\fmetadataJson\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\tR\ttimestampB\tZ\a./protob\x06proto3"

var (
	file_proto_agent_events_proto_rawDescOnce sync.Once
	file_proto_agent_events_proto_rawDescData []byte
)

func file_proto_agent_events_proto_rawDescGZIP() []byte {
	file_proto_agent_events_proto_rawDescOnce.Do(func() {
		file_proto_agent_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_events_proto_rawDesc), len(file_proto_agent_events_proto_rawDesc)))
	})
	return file_proto_agent_events_proto_rawDescData
}

var file_proto_agent_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_agent_events_proto_goTypes = []any{
	(*AgentRequestEvent)(nil),  // 0: agent.AgentRequestEvent
	(*AgentResponseEvent)(nil), // 1: agent.AgentResponseEvent
}
var file_proto_agent_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_agent_events_proto_init() }
func file_proto_agent_events_proto_init() {
	if File_proto_agent_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_events_proto_rawDesc), len(file_proto_agent_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agent_events_proto_goTypes,
		DependencyIndexes: file_proto_agent_events_proto_depIdxs,
		MessageInfos:      file_proto_agent_events_proto_msgTypes,
	}.Build()
	File_proto_agent_events_proto = out.File
	file_proto_agent_events_proto_goTypes = nil
	file_proto_agent_events_proto_depIdxs = nil
}
